FROM mysql:latest

ENV MYSQL_PWD=root

#RUN rm -rf /var/lib/mysql
#RUN mkdir -p /var/lib/mysql /var/run/mysqld
#RUN chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
#RUN chmod 777 /var/run/mysqld
#COPY dump.sql /var/lib/mysql/dump.sql

#RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &"
#RUN sleep 5
#RUN mysql -u root -e "CREATE DATABASE phalcon3"
#RUN mysql -u root phalcon3 < /var/lib/mysql/dump.sql

EXPOSE 33060 3306