version: "3.4"
x-custom:
  shared_env: &shared_env
    AWS_KEY: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET: ${AWS_SECRET_ACCESS_KEY}

services:

    nginx:
      container_name: nginx
      working_dir: /phalcon3
      build: ./environment/nginx
      privileged: true
      volumes:
          - .:/phalcon3
          - ./environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"
      env_file:
        - '.env'
      links:
        - php-fpm

    php-fpm:
      container_name: php-fpm
      privileged: true
      working_dir: /phalcon3
      build: ./environment/php-7
      volumes:
        - .:/phalcon3
        - ./environment/php-7/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      env_file:
        - '.env'
      environment:
        PHP_IDE_CONFIG: "serverName=docker"
        <<: *shared_env
      links:
        - redis

    redis:
      container_name: redis
      privileged: true
      build: ./environment/redis
      env_file:
        - '.env'
      ports:
        - 6380:6379
      deploy:
        resources:
          limits:
            memory: 1g

    mysql:
      container_name: mysql
      build: ./environment/mysql
      #privileged: true
      #restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        #- MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_DATABASE=phalcon3
        - MYSQL_USER=root
        - MYSQL_PASSWORD=753159
        - MYSQL_ROOT_PASSWORD=753159
      ports:
        - "33060:3306"
volumes:
  db_data: {}