###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
#x-custom:
#  shared_env: &shared_env
#    AWS_KEY: ${AWS_ACCESS_KEY_ID}
#    AWS_SECRET: ${AWS_SECRET_ACCESS_KEY}

services:

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /phalcon3
      volumes:
          - .:/phalcon3
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /phalcon3
      volumes:
        - .:/phalcon3
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        PHP_IDE_CONFIG: "serverName=docker"
#        <<: *shared_env
#    mysql_db:
#      image: mysql:5.7
#      volumes:
#        - db_data:/var/lib/mysql
#        - ./phpdocker/database:/dump/
#      restart: always
#      command: --sql_mode="NO_ENGINE_SUBSTITUTION"
#      environment:
#        MYSQL_ROOT_PASSWORD: root
#        MYSQL_DATABASE: deadpool_dev
#        MYSQL_USER: deadpool_dev
#        MYSQL_PASSWORD: deadpool_dev
#      ports:
#        - "33066:3306"