###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
#x-custom:
#  shared_env: &shared_env
#    AWS_KEY: ${AWS_ACCESS_KEY_ID}
#    AWS_SECRET: ${AWS_SECRET_ACCESS_KEY}

services:

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /phalcon3
      volumes:
          - .:/phalcon3
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /phalcon3
      volumes:
        - .:/phalcon3
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        PHP_IDE_CONFIG: "serverName=docker"
#        <<: *shared_env

    mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      #command: --sql_mode="NO_ENGINE_SUBSTITUTION"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=753159
        - MYSQL_DATABASE=phalcon3
        - MYSQL_USER=root
        - MYSQL_PASSWORD=753159
      ports:
        - "3306:3306"

    redis:
      image: redis:3.2-alpine
      container_name: redis
      ports:
        - "63792:6379"